@startuml
class AddMessageEffect {
}
class AddMessageEffectApplier {
    + AddMessageEffectApplier(botClient:ITelegramBotClient)
    + <<async>> Apply(effect:EffectBase) : Task
}
class "IEffectApplier`1"<T> {
}
EffectBase <|-- AddMessageEffect
"IEffectApplier`1" "<AddMessageEffect>" <|-- AddMessageEffectApplier
AddMessageEffectApplier --> "_botClient" ITelegramBotClient
@enduml
