@startuml
class RemoveMessageEffect {
}
class RemoveMessageEffectApplier {
    + RemoveMessageEffectApplier(botClient:ITelegramBotClient)
    + <<async>> Apply(effect:RemoveMessageEffect) : Task
    + Apply(effect:EffectBase) : Task
}
class "IEffectApplier`1"<T> {
}
EffectBase <|-- RemoveMessageEffect
"IEffectApplier`1" "<RemoveMessageEffect>" <|-- RemoveMessageEffectApplier
RemoveMessageEffectApplier --> "_botClient" ITelegramBotClient
@enduml
