@startuml
class BotDbContext {
    + BotDbContext()
    # <<override>> OnConfiguring(optionsBuilder:DbContextOptionsBuilder) : void
    # <<override>> OnModelCreating(modelBuilder:ModelBuilder) : void
}
class "DbSet`1"<T> {
}
DbContext <|-- BotDbContext
BotDbContext o-> "InnerUsers<InnerUser>" "DbSet`1"
BotDbContext o-> "ChatScopes<ChatScope>" "DbSet`1"
BotDbContext o-> "Posts<Post>" "DbSet`1"
BotDbContext o-> "Buttons<ButtonBase>" "DbSet`1"
BotDbContext o-> "Triggers<Trigger>" "DbSet`1"
@enduml
