@startuml
class SqlInnerUserStorage {
    + SqlInnerUserStorage(dbContext:BotDbContext)
    + <<async>> IsInnerUserExist(user:User) : ValueTask<bool>
    + <<async>> CreateInnerUser(user:User) : ValueTask<InnerUser>
    + <<async>> RetrieveInnerUser(user:User) : ValueTask<InnerUser>
    + <<async>> CommitInnerUser(user:InnerUser) : ValueTask
}
IInnerUserStorge <|-- SqlInnerUserStorage
SqlInnerUserStorage --> "_dbContext" BotDbContext
@enduml
