@startuml
interface ITextSetterDispatcher {
    ResolveAsync(setter:T) : Task<string>
}
class TextSetterDispatcher <<sealed>> {
    + TextSetterDispatcher(provider:IServiceProvider)
    + <<async>> ResolveAsync(setter:T) : Task<string>
}
ITextSetterDispatcher <|-- TextSetterDispatcher
TextSetterDispatcher --> "_provider" IServiceProvider
TextSetterDispatcher o-> "Generic" Type
@enduml
