@startuml
class Text {
    + TextId : int <<get>> <<set>>
    + OriginalText : string <<get>> <<set>>
    + OriginalEntities : ICollection<MessageEntity>? <<get>> <<set>>
    + PlainText : string? <<get>> <<set>>
    + PreparedText : string? <<get>> <<set>>
    + Surrogates : ICollection<TextSetterBase>? <<get>> <<set>>
    + Text()
    + Text(text:string)
}
@enduml
