@startuml
class InputService {
    + InputService(chatScopeStorage:IChatScopeStorage, dialogeService:IDialogueService, autoInput:IAutoInput)
    + <<async>> IsThereAnyActiveDialogue(user:InnerUser) : ValueTask<bool>
    + AssignFromTriggerAsync(user:InnerUser, trigger:Trigger) : ValueTask
    + AssignFromTriggerAsync(user:InnerUser, trigger:Trigger, message:InnerMessage) : ValueTask
    + AssignFromConcreteMessage(user:InnerUser, messageId:int, data:string) : ValueTask
}
IInputService <|-- InputService
InputService --> "_chatScopeStorage" IChatScopeStorage
InputService --> "_dialogeService" IDialogueService
InputService --> "_autoInput" IAutoInput
@enduml
