@startuml
class ChatFlowService {
    + ChatFlowService(innerUserStorage:IInnerUserStorge, chatScopeService:IChatScopeService, triggerService:ITriggerService, validationService:IValidationService, inputService:IInputService)
    + <<async>> SubmitCallbackQueryAsync(callbackQuery:CallbackQuery) : ValueTask<InnerUserState>
    + <<async>> SubmitMediaGroupAsync(mediaGroup:IEnumerable<Message>) : ValueTask<InnerUserState>
    + <<async>> SubmitMessageAsync(message:Message) : ValueTask<InnerUserState>
    - <<async>> SubmitInnerMessage(user:User, innerMessage:InnerMessage) : ValueTask<InnerUserState>
}
IChatFlowService <|-- ChatFlowService
ChatFlowService --> "_innerUserStorage" IInnerUserStorge
ChatFlowService --> "_chatScopeService" IChatScopeService
ChatFlowService --> "_triggerService" ITriggerService
ChatFlowService --> "_validationService" IValidationService
ChatFlowService --> "_inputService" IInputService
@enduml
