@startuml
class Media {
    + MediaId : int <<get>> <<set>>
    + FileId : string? <<get>> <<set>>
    + FileUniqueId : string? <<get>> <<set>>
    + Path : string? <<get>> <<set>>
    + BotName : string? <<get>> <<set>>
    + Media(mediaType:MediaType, fileId:string?, fileUniqueId:string?, path:string?)
}
Media --> "MediaType" MediaType
@enduml
