@startuml
class ChatScopeService {
    + ChatScopeService(chatScopeStorage:IChatScopeStorage, triggerService:ITriggerService)
    + <<async>> CleanScopeAsync(user:InnerUser) : ValueTask
    + <<async>> HasCorrectionLoop(user:InnerUser) : ValueTask<bool>
    + GetActiveInputReasonAsync(user:InnerUser) : ValueTask<Post?>
    + SetInputToActiveAsync(user:InnerUser, message:InnerMessage) : ValueTask
    + SetInputToReasonAsync(user:InnerUser, trigger:Trigger, message:InnerMessage) : ValueTask
}
IChatScopeService <|-- ChatScopeService
ChatScopeService --> "_chatScopeStorage" IChatScopeStorage
ChatScopeService --> "_triggerService" ITriggerService
@enduml
