@startuml
class SqlChatScopeStorage {
    + SqlChatScopeStorage(botDbContext:BotDbContext)
    + CreateChatScope(user:User) : ValueTask<ChatScope>
    + RetrieveChatScope(user:InnerUser) : ValueTask<ChatScope>
    + CommitChatScope(chatScope:ChatScope) : ValueTask
}
IChatScopeStorage <|-- SqlChatScopeStorage
SqlChatScopeStorage --> "_botDbContext" BotDbContext
@enduml
