@startuml
interface ITriggerService {
    ExecuteAsync(user:InnerUser, trigger:Trigger) : ValueTask
    ExecuteAsync(user:InnerUser, effect:EffectBase) : ValueTask
    FromValidCustomInput(user:InnerUser) : ValueTask<Trigger?>
    FromInvalidCustomInput(user:InnerUser) : ValueTask<Trigger?>
    FromPlainPreparedAsync(user:InnerUser, prepared:string) : ValueTask<Trigger?>
    FromEncodedPreparedAsync(user:InnerUser, encodedId:string) : ValueTask<Trigger?>
    FromEncodedStoredAsync(user:InnerUser, encodedId:string) : ValueTask<Trigger?>
    IntoEncodedId(user:InnerUser, trigger:Trigger) : string
}
@enduml
