@startuml
enum InnerMessageType {
    Text,
    TextFromButton,
    Photo,
    Video,
    VideoNote,
    Voice,
    Audio,
    Animation,
    Sticker,
    Document,
    Contact,
    Geolocation,
    PhotoVideoAlbum,
    AudioAlbum,
    DocumentAlbum,
    Unsupported,
}
@enduml
