@startuml
class ShowedMessage {
    + ShowedMessageId : int <<get>> <<set>>
    + CauseMessageId : int? <<get>> <<set>>
    + Label : string? <<get>> <<set>>
    + Text : Text? <<get>> <<set>>
    + Media : ICollection<Media>? <<get>> <<set>>
    + RecievedFromUser : ICollection<InnerMessage>? <<get>> <<set>>
}
ILabeled <|-- ShowedMessage
ShowedMessage --> "Type" InnerMessageType
@enduml
